markdown: rdiscount
permalink: /left/posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Katie Ball
url: http://roachhd.github.io/left
description: A fantastic List that is fantastic.
twitter: mektball
